In [1]:
import pandas as pd

### Data exploration

In [2]:
restaurants = pd.read_csv("../data/csv_files/restaurants.csv")
restaurants.head()

  restaurant_id   cuisine        city  rating
0          R001    Indian  Manchester     3.4
1          R002   Chinese       Leeds     4.1
2          R003   Chinese       Leeds     4.1
3          R004      Thai  Birmingham     3.5
4          R005  American     Bristol     4.3

## Ingestion de las tablas

In [8]:
import pandas as pd
from sqlalchemy import create_engine

In [5]:
engine = create_engine(
    "postgresql+psycopg2://postgres:1603@localhost:5432/food_platform"
)

In [10]:
files = {
    "restaurants": "../data/csv_files/restaurants.csv",
    "menu_items": "../data/csv_files/menu_items.csv",
    "orders_medium": "../data/csv_files/orders_medium.csv",
    "order_items": "../data/csv_files/order_items (2).csv",
    "customers_medium": "../data/csv_files/customers_medium.csv",
}

In [11]:
for table_name, file_path in files.items():
    df = pd.read_csv(file_path)
    
    df.to_sql(
        name=table_name,
        con=engine,
        schema="raw",
        if_exists="replace",  # 'replace' sobreescribe la tabla si la vuelves a ejecutar
        index=False
    )

In [12]:
df_test = pd.read_sql("SELECT * FROM raw.restaurants LIMIT 5;", con=engine)
print(df_test)

  restaurant_id   cuisine        city  rating
0          R001    Indian  Manchester     3.4
1          R002   Chinese       Leeds     4.1
2          R003   Chinese       Leeds     4.1
3          R004      Thai  Birmingham     3.5
4          R005  American     Bristol     4.3

# 03 Transformation Test

This notebook is used to prototype the transformation logic before converting it into PostgreSQL stored procedures.

For each table, the structure is:

```text
1. Query the raw table
2. Apply the transformation SELECT statement

```

In order to compare the raw output with the transformed output

In [15]:
from pathlib import Path
import sys
import pandas as pd

BASE_DIR = Path.cwd().parent
SRC_DIR = BASE_DIR / "src"

sys.path.append(str(SRC_DIR))

from db_connection import  get_engine

engine = get_engine()

2026-09-16 20:26:05,171 | INFO | db_connection | Database environment variables validated successfully.
2026-09-16 20:26:05,214 | INFO | db_connection | Building database URL for host=localhost, port=5432, database=food_platform, user=postgres
2026-09-16 20:26:05,229 | INFO | db_connection | Creating SQLAlchemy engine.

In [16]:
def run_query(query: str) -> pd.DataFrame:
    with engine.connect() as connection:
        return pd.read_sql(query, connection)

In [19]:
raw_restaurants_query = """
SELECT 
    restaurant_id,
    TRIM(cuisine) AS cuisine,
    TRIM(city) AS city,
    rating
FROM raw.restaurants
WHERE restaurant_id IS NOT NULL
ORDER BY restaurant_id;
"""

raw_restaurants_df = run_query(raw_restaurants_query)
raw_restaurants_df.head(10)

  restaurant_id   cuisine        city  rating
0          R001    Indian  Manchester     3.4
1          R002   Chinese       Leeds     4.1
2          R003   Chinese       Leeds     4.1
3          R004      Thai  Birmingham     3.5
4          R005  American     Bristol     4.3
5          R006  American       Leeds     3.3
6          R007    Indian  Manchester     3.3
7          R008   Mexican       Leeds     3.4
8          R009   Mexican     Bristol     4.9
9          R010   Mexican      London     4.7